apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "KubeLinks.fullname" . }}
  labels:
    {{- include "KubeLinks.labels" . | nindent 4 }}
data:
  extraUrls.yaml: |-
{{- if .Values.extraUrls }}
    {{- toYaml $.Values.extraUrls | nindent 4 }}
{{- end }}
  urlFilters.yaml: |-
{{- if .Values.urlFilters }}
    {{- toYaml $.Values.urlFilters | nindent 4 }}
{{- end }}
