name: Python application

on:
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read


jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install -r requirements.txt
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |         
        python -m pytest
      env:
        FLASK_APP: kubelinks_app.__init__
    - name: Build without push
      uses: docker/build-push-action@v3
      with:
        context: .
        push: false
        tags: smitkirara/kubelinks:v0.0.${{ github.run_number }}-dev
